UNIT ANALISIS_LEXICO;

INTERFACE

USES TYPES,CRT;

{ANALISIS}
PROCEDURE ESPACIO(VAR C:STRING);
FUNCTION COMPLEXVALIDO(var CARA:char):BOOLEAN;

IMPLEMENTATION

PROCEDURE ESPACIO(VAR C:STRING); {BORRA ESPACIOS}
VAR i:INTEGER;
begin
i:=(pos(' ',C));
  IF i = 0 THEN
  Exit;
DELETE(C,i,1);
ESPACIO(C);
end;

FUNCTION COMPLEXVALIDO(var CARA:char):BOOLEAN;
	BEGIN
		IF CARA IN CARACTER THEN
			COMPLEXVALIDO:=TRUE
		ELSE
		BEGIN
			CASE CARA OF
				'<':COMPLEXVALIDO:=TRUE;
				'>':COMPLEXVALIDO:=TRUE;
				'&':COMPLEXVALIDO:=TRUE;
				'~':COMPLEXVALIDO:=TRUE;
				'^':COMPLEXVALIDO:=TRUE;
				'!':COMPLEXVALIDO:=TRUE;
				'|':COMPLEXVALIDO:=TRUE;
			ELSE
			COMPLEXVALIDO:=FALSE;
			END;
		END;
	END;


BEGIN
END.
