PROGRAM LEFP;
USES CRT,TYPES,ENTORNO,UAFNe,UARBOL,UARCHIVO,UPILA,UTAS,DVL,menu,ANALISIS_LEXICO;
VAR
ER:STRING;
ARCHIVO:T_ARCHIVO;
RESALTE,N,Y,F,C,D:INTEGER;
OP:CHAR;
ARCH_ER:t_archivo;
ARBOL:t_arbol;
CONTINUAR:boolean;
AFNe:AFN;
AFDNMin,AFDMin:AFD;
BEGIN
BIENVENIDA;
CLRSCR;
Op:='A';
RESALTE:=10;
Repeat
	Repeat
	PRINCIPAL;
	n:=7;
	y:=1;
			Repeat
				MENU_PRINCIPAL(N,Y,OP);
			until (Op = #13);

			Case y of
			1:BEGIN
			GOTOXY(120,5);
			TEXTCOLOR(0);
			Writeln('Ingresar nueva ER ');
			GOTOXY(120,7);
			TEXTCOLOR(14);
			READ(ER);
			ESPACIO(ER);
			ESCRIBIR(ARCHIVO,ER);
			CLRSCR;
			END;

			2:BEGIN
			F:=7;
			C:=100;
			GOTOXY(120,5);
			ER:='';
			TEXTCOLOR(0);
			Writeln(' Modificando ');
			TEXTCOLOR(14);
			LEER1(ARCHIVO,ER);
			MODIFICAR(ER,F,C);
			ESPACIO(ER);
			ESCRIBIR(ARCHIVO,ER);
			CLRSCR; 
			END;

			3:BEGIN
			F:=5;
			C:=120;
			DIBUJAR_GRAMATICA(F,C);
			F:=27;
			C:=94;
			GOTOXY(134,22);
			TEXTCOLOR(0);
			WRITELN('T A S');
			TEXTCOLOR(14);
			DIBUJAR_TAS(F,C);
			READKEY;
			END;

			4: BEGIN
			D:=600;
			F:=3;
			C:=120;
			GOTOXY(C,F);
			WRITELN('REALIZANDO ANALISIS LEXICO');DELAY(D);C:=C+27;GOTOXY(C,F);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');
			INC(F);
			INC(F);
			C:=120;
			gotoxy(c,f);
			WRITELN('REALIZANDO ANALISIS SINTACTICO');DELAY(D);C:=C+31;GOTOXY(C,F);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');
			INC(F);
			INC(F);
			C:=120;
			gotoxy(c,f);
			WRITELN('GENERANDO ARBOL SINTACTICO');DELAY(D);C:=C+27;GOTOXY(C,F);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');
			INC(F);
			INC(F);
			C:=120;
			gotoxy(c,f);
			WRITELN('REALIZANDO AFN-e');DELAY(D);C:=C+17;GOTOXY(C,F);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');
			INC(F);
			INC(F);
			C:=120;
			gotoxy(c,f);
			WRITELN('REALIZANDO AFD');DELAY(D);C:=C+14;GOTOXY(C,F);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');
			INC(F);
			INC(F);
			C:=120;
			gotoxy(c,f);
			WRITELN('GENERANDO AFD MINIMO');DELAY(D);C:=C+21;GOTOXY(C,F);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);WRITE('.');INC(C);GOTOXY(C,F);DELAY(D);TEXTCOLOR(5);WRITE('[RECIENTE]');
			F:=F+15;
			GOTOXY(C-15,F);TEXTCOLOR(5);
			WRITELN('LA ULTIMA ACCION SE HA PROGRAMADO EN LAS ULTIMAS HORAS');
			TEXTCOLOR(14);
			INC(F);
			INC(F);
			GOTOXY(C-30,F);
			WRITELN('LAS TABLAS DE TRANSICION SE ENCUENTRAN EN LA CARPETA ');
			INC(F);
			GOTOXY(C-30,F);
			WRITELN('       RECURSOS CON SUS RESPECTIVOS NOMBRES');
			READKEY;
			
			AN_SINTACTICO(ARCH_ER,ARBOL,CONTINUAR);
			CERRAR(ARCH_ER);
				IF CONTINUAR THEN
				BEGIN
				GENERAR_AFNe(ARBOL,AFNe);
				GRABARAFN(AFNe);
				GENERAR_AFD(AFNe,AFDNMin);
				GRABARAFD(AFDNMin);
				GENERAR_AFDM(AFDNMin,AFDMin);
				GRABARAFDMin(AFDMin);
				END;
			END;

			5:BEGIN
			F:=20;
			C:=120;
			GOTOXY(C-10,F);TEXTCOLOR(5);
			WRITELN('EL AFD MINIMO SE HA PROGRAMADAO EN LAS ULTIMAS HORAS');
			TEXTCOLOR(14);
			INC(F);
			INC(F);
			GOTOXY(C-7,F);
			WRITELN('LAS TABLAS DE TRANSICION SE ENCUENTRAN EN LA CARPETA ');
			INC(F);
			GOTOXY(C-7,F);
			WRITELN('       RECURSOS CON SUS RESPECTIVOS NOMBRES');
			F:=F+3;
			C:=105;
			GOTOXY(C-7,F);
			TEXTCOLOR(0);
			WRITE('*');INC(C);
			TEXTCOLOR(14);
			WRITELN('SE REALIZARON LAS SIGUIENTES ACCIONES: ');INC(F);INC(F);
			C:=120;
			GOTOXY(C+15,F);
			WRITELN('ANALISIS LEXICO');INC(F);INC(F);
			GOTOXY(C+15,F);
			WRITELN('ANALISIS SINTACTICO');INC(F);INC(F);
			GOTOXY(C+15,F);
			WRITELN('DESARROLLO ARBOL SINTACTICO');INC(F);INC(F);
			GOTOXY(C+15,F);
			WRITELN('GENERAR AFD-e');INC(F);INC(F);
			GOTOXY(C+15,F);
			WRITELN('GENERAR AFD');INC(F);INC(F);
			GOTOXY(C+15,F);
			WRITELN('GENERANDO AFD MINIMO');TEXTCOLOR(5);GOTOXY(C+37,F);WRITE('[RECIENTE]');TEXTCOLOR(14);
			READKEY;
			AN_SINTACTICO(ARCH_ER,ARBOL,CONTINUAR);
			CERRAR(ARCH_ER);
				IF CONTINUAR THEN
				BEGIN
				GENERAR_AFNe(ARBOL,AFNe);
				GRABARAFN(AFNe);
				GENERAR_AFD(AFNe,AFDNMin);
				GRABARAFD(AFDNMin);
				GENERAR_AFDM(AFDNMin,AFDMin);
				GRABARAFDMin(AFDMin);
				END;
			END;

				6:BEGIN
					MENU_INFORME;
				END;
		END;
	Until (Op=#13);
Until (y=7);
END.
